### ISSUE TITLE
missing value for Cloak protector

### ISSUE THREAD

**Issue by lintangtimur** [MrDimaseS/EBF-Reborn2#2]
https://github.com/MrDimaseS/EBF-Reborn2/blob/355cea70e2105caa7afe7529ac80357639ddde87/game/dota_addons/ebf/scripts/vscripts/items/item_cloak_of_the_protector.lua#L119

block_chance
block_range
block_melee

**Comment by Yahnich** [comment]
block on cloak is deprecated as its now built from pavise, tooltip will be adjusted
